/// <reference types="vite/client" />

/**
 * Nothing in this app had read `import.meta.env` before the PayPal integration —
 * every other VITE_ variable in .env.example is consumed at build time by other tooling,
 * not read directly in application code — so this reference file (Vite's standard
 * scaffold file, generated by `npm create vite` but never added here) didn't exist yet.
 * The explicit ImportMetaEnv fields below aren't required for `import.meta.env.X` to
 * type-check (Vite's own ambient types already provide a permissive index signature) but
 * document the one env var this app's code actually reads.
 */
interface ImportMetaEnv {
  /** PayPal's public client id — see apps/web/src/lib/paypalSdk.ts. Not a secret. */
  readonly VITE_PAYPAL_CLIENT_ID?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
