/**
 * Explicit icon registry — named imports only, one per icon actually used in the app.
 *
 * The first version of this component imported lucide-react's blanket `icons` map,
 * which pulls in every one of its ~1,500 icons regardless of how many are actually
 * used — that produced a 934KB main bundle in the very first production build of this
 * sprint, directly contradicting the "tree-shakable, one import per icon" claim in
 * docs/build/01-BRAND-SYSTEM.md §5 and the performance budget in
 * docs/build/09-SEO-PERFORMANCE-CHECKLIST.md §5. This file is the fix: only icons
 * listed here ever end up in the bundle.
 *
 * Add a new icon by adding one named import + one map entry — never widen this back to
 * the blanket `icons` object.
 */
import {
  ArrowRight,
  Award,
  BadgeCheck,
  Box,
  Briefcase,
  Building2,
  Calendar,
  ChevronDown,
  ChevronUp,
  Clock,
  Compass,
  ConciergeBell,
  Cross,
  Crown,
  DollarSign,
  Eye,
  Factory,
  FileText,
  Flame,
  FlameKindling,
  GraduationCap,
  Hammer,
  Heart,
  Landmark,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Package,
  Phone,
  Plane,
  Recycle,
  Rocket,
  Server,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SprayCan,
  SquareParking,
  Target,
  Theater,
  TrendingUp,
  User,
  Users,
  Utensils,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  box: Box,
  briefcase: Briefcase,
  'building-2': Building2,
  building: Building2,
  calendar: Calendar,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  clock: Clock,
  compass: Compass,
  'concierge-bell': ConciergeBell,
  cross: Cross,
  crown: Crown,
  'dollar-sign': DollarSign,
  eye: Eye,
  factory: Factory,
  'file-text': FileText,
  flame: Flame,
  'flame-kindling': FlameKindling,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  heart: Heart,
  landmark: Landmark,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  package: Package,
  phone: Phone,
  plane: Plane,
  recycle: Recycle,
  rocket: Rocket,
  server: Server,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'spray-can': SprayCan,
  'square-parking': SquareParking,
  target: Target,
  theater: Theater,
  'trending-up': TrendingUp,
  user: User,
  users: Users,
  utensils: Utensils,
  wrench: Wrench,
  x: X,
  zap: Zap,
};
